language: php

notifications:
  email:
    recipients:

sudo: false

addons:
  postgresql: "9.6"

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 7.3

git:
  depth: false

env:
  global:
    - DB=pgsql
  matrix:
    - MOODLE_BRANCH=MOODLE_35_STABLE
    - MOODLE_BRANCH=MOODLE_36_STABLE
    - MOODLE_BRANCH=MOODLE_37_STABLE
    - MOODLE_BRANCH=MOODLE_38_STABLE
    - MOODLE_BRANCH=master

matrix:
  include:
    # Test with MySQL
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    # Test with PHP 7.1
    - php: 7.1
      env: MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.3
      env: MOODLE_BRANCH=master
      before_install:
        - >
          if [ "$TRAVIS_PULL_REQUEST" != 'false' ]; then
            cd ../..;
            composer selfupdate;
            composer create-project -n --no-dev peterburnett/moodle-plugin-ci-testing ci dev-master;
            export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH";
          fi
      install:
        - >
          if [ "$TRAVIS_PULL_REQUEST" != 'false' ]; then
            moodle-plugin-ci install -vvv;
            (cd moodle/admin/tool/abconfig; git checkout $TRAVIS_BRANCH;);
            php moodle/admin/cli/install_database.php --agree-license --adminpass=null;
          fi
      script:
        - >
          if [ "$TRAVIS_PULL_REQUEST" != 'false' ]; then
            (cd moodle/admin/tool/abconfig; git checkout $TRAVIS_COMMIT;);
            php moodle/admin/cli/upgrade.php --non-interactive --allow-unstable;
            moodle-plugin-ci checkdbschema;
          fi


  exclude:
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_34_STABLE
    - php: 7.3
      env: MOODLE_BRANCH=MOODLE_35_STABLE


before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev peterburnett/moodle-plugin-ci-testing ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci validate
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci
