#
# Whenever version.php is changed, add the latest version
# to the Moodle Plugins directory at https://moodle.org/plugins
#
name: Releasing in the Plugins directory

on:
  push:
    branches:
      - master
    paths:
      - 'version.php'

jobs:
  workflow_group_38_plus_release:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/group-38-plus-release.yml@main
    with:
      plugin_name: tool_abconfig
    secrets:
      moodle_org_token: ${{ secrets.MOODLE_ORG_TOKEN }}
